/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/dji-fpv-by-sdc-high-performance-drone-d471ea8c6235457b8e131842e2cf3783
title: Dji FPV by SDC -  High performance drone
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/drone.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 1.02, -0.14]} rotation={[-0.48, 0, 0]} scale={3.53}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.28}>
              <mesh geometry={nodes.Object_5.geometry} material={materials.M_D1} />
              <mesh geometry={nodes.Object_6.geometry} material={materials.Plastic_D1} />
              <mesh geometry={nodes.Object_7.geometry} material={materials.Plastic_L1} />
              <mesh geometry={nodes.Object_8.geometry} material={materials.Plastic_D2} />
              <mesh geometry={nodes.Object_9.geometry} material={materials.Metall_Basic} />
              <mesh geometry={nodes.Object_10.geometry} material={materials['Material.009']} />
            </group>
            <group scale={0.28}>
              <mesh geometry={nodes.Object_12.geometry} material={materials.Material} />
            </group>
            <group position={[0, -0.01, 0]} scale={0.28}>
              <mesh geometry={nodes.Object_14.geometry} material={materials['Material.007']} />
            </group>
            <group rotation={[0.42, 0.02, 0.08]} scale={0.28}>
              <mesh geometry={nodes.Object_16.geometry} material={materials.Grey_L1} />
              <mesh geometry={nodes.Object_17.geometry} material={materials.Grey_Basic} />
              <mesh geometry={nodes.Object_18.geometry} material={materials['Material.005']} />
              <mesh geometry={nodes.Object_19.geometry} material={materials.Grey_D2} />
              <mesh geometry={nodes.Object_20.geometry} material={materials.Plastic_D1} />
            </group>
            <group rotation={[0.5, 0, 0]} scale={0.28}>
              <mesh geometry={nodes.Object_22.geometry} material={materials.Rubber_L1} />
              <mesh geometry={nodes.Object_23.geometry} material={materials.Rubber_Basic} />
              <mesh geometry={nodes.Object_24.geometry} material={materials.Rubber_D1} />
            </group>
            <group rotation={[0.45, 0, 0]} scale={0.28}>
              <mesh geometry={nodes.Object_26.geometry} material={materials.Plastic_D1} />
              <mesh geometry={nodes.Object_27.geometry} material={materials.Rubber_Basic} />
              <mesh geometry={nodes.Object_28.geometry} material={materials.Plastic_D2} />
            </group>
            <group rotation={[0.62, 0, 0]} scale={0.28}>
              <mesh geometry={nodes.Object_30.geometry} material={materials.Grey_D2} />
              <mesh geometry={nodes.Object_31.geometry} material={materials.Plastic_D1} />
              <mesh geometry={nodes.Object_32.geometry} material={materials.Rubber_Basic} />
              <mesh geometry={nodes.Object_33.geometry} material={materials.Plastic_L2} />
              <mesh geometry={nodes.Object_34.geometry} material={materials.Plastic_L1} />
              <mesh geometry={nodes.Object_35.geometry} material={materials.Plastic_Base} />
              <mesh geometry={nodes.Object_36.geometry} material={materials.Plastic_D2} />
              <mesh geometry={nodes.Object_37.geometry} material={materials['Material.004']} />
              <mesh geometry={nodes.Object_38.geometry} material={materials['Material.013']} />
            </group>
            <group scale={0.28}>
              <mesh geometry={nodes.Object_40.geometry} material={materials.M_L1} />
              <mesh geometry={nodes.Object_41.geometry} material={materials.Grey_D1} />
              <mesh geometry={nodes.Object_42.geometry} material={materials.Plastic_Base} />
            </group>
            <group scale={0.28}>
              <mesh geometry={nodes.Object_44.geometry} material={materials.Grey_L1} />
              <mesh geometry={nodes.Object_45.geometry} material={materials.Grey_Basic} />
              <mesh geometry={nodes.Object_46.geometry} material={materials['Material.005']} />
              <mesh geometry={nodes.Object_47.geometry} material={materials.Grey_D2} />
            </group>
            <group scale={0.28}>
              <mesh geometry={nodes.Object_49.geometry} material={materials.Grey_D1} />
              <mesh geometry={nodes.Object_50.geometry} material={materials.CARBONE} />
            </group>
            <group scale={0.28}>
              <mesh geometry={nodes.Object_52.geometry} material={materials['Material.006']} />
            </group>
            <group rotation={[1.12, 0, 0]} scale={0.28}>
              <mesh geometry={nodes.Object_54.geometry} material={materials['Material.014']} />
            </group>
            <group scale={0.28}>
              <mesh geometry={nodes.Object_56.geometry} material={materials.Plastic_D1} />
              <mesh geometry={nodes.Object_57.geometry} material={materials.Plastic_L1} />
              <mesh geometry={nodes.Object_58.geometry} material={materials.Plastic_Base} />
            </group>
            <group scale={0.28}>
              <mesh geometry={nodes.Object_60.geometry} material={materials.Plastic_D1} />
              <mesh geometry={nodes.Object_61.geometry} material={materials.Rubber_L1} />
              <mesh geometry={nodes.Object_62.geometry} material={materials.Plastic_L1} />
            </group>
            <group scale={0.28}>
              <mesh geometry={nodes.Object_64.geometry} material={materials.M_D1} />
              <mesh geometry={nodes.Object_65.geometry} material={materials.Plastic_D1} />
              <mesh geometry={nodes.Object_66.geometry} material={materials.Plastic_Base} />
            </group>
            <group rotation={[0.64, 0, 0]} scale={0.28}>
              <mesh geometry={nodes.Object_68.geometry} material={materials.Metall_D2} />
            </group>
            <group scale={0.28}>
              <mesh geometry={nodes.Object_70.geometry} material={materials.Mettal_L1} />
              <mesh geometry={nodes.Object_71.geometry} material={materials.Metall_Basic} />
              <mesh geometry={nodes.Object_72.geometry} material={materials.Metall_D1} />
            </group>
            <group scale={0.28}>
              <mesh geometry={nodes.Object_74.geometry} material={materials.Plastic_D1} />
              <mesh geometry={nodes.Object_75.geometry} material={materials.Plastic_L1} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.32, 0.28, 0.28]}>
              <mesh geometry={nodes.Object_77.geometry} material={materials.Plastic_Base} />
              <mesh geometry={nodes.Object_78.geometry} material={materials.Metall_D2} />
            </group>
            <group scale={0.28}>
              <mesh geometry={nodes.Object_80.geometry} material={materials.Grey_D1} />
              <mesh geometry={nodes.Object_81.geometry} material={materials.Grey_D2} />
            </group>
            <group scale={0.28}>
              <mesh geometry={nodes.Object_83.geometry} material={materials.Grey_Basic} />
              <mesh geometry={nodes.Object_84.geometry} material={materials.Grey_D1} />
              <mesh geometry={nodes.Object_85.geometry} material={materials.Grey_D2} />
            </group>
            <group scale={0.28}>
              <mesh geometry={nodes.Object_87.geometry} material={materials.Green_L1} />
              <mesh geometry={nodes.Object_88.geometry} material={materials.Green_L2E} />
            </group>
            <group rotation={[1.12, 0, 0]} scale={0.28}>
              <mesh geometry={nodes.Object_90.geometry} material={materials.Rubber_Basic} />
              <mesh geometry={nodes.Object_91.geometry} material={materials.Rubber_D1} />
              <mesh geometry={nodes.Object_92.geometry} material={materials.Plastic_L2} />
            </group>
            <group rotation={[0.64, 0, 0]} scale={0.28}>
              <mesh geometry={nodes.Object_94.geometry} material={materials.M_Basic} />
              <mesh geometry={nodes.Object_95.geometry} material={materials.M_D1} />
              <mesh geometry={nodes.Object_96.geometry} material={materials.M_D2} />
              <mesh geometry={nodes.Object_97.geometry} material={materials.Plastic_D1} />
              <mesh geometry={nodes.Object_98.geometry} material={materials.Plastic_L1} />
              <mesh geometry={nodes.Object_99.geometry} material={materials.Plastic_Base} />
            </group>
            <group scale={0.28}>
              <mesh geometry={nodes.Object_101.geometry} material={materials.Red_L1} />
              <mesh geometry={nodes.Object_102.geometry} material={materials.Red_Basic} />
              <mesh geometry={nodes.Object_103.geometry} material={materials.Red_D1} />
              <mesh geometry={nodes.Object_104.geometry} material={materials.Grey_L1} />
            </group>
            <group scale={0.28}>
              <mesh geometry={nodes.Object_106.geometry} material={materials['Material.016']} />
            </group>
            <group rotation={[0, 0, -Math.PI / 2]} scale={0.27}>
              <mesh geometry={nodes.Object_108.geometry} material={materials.M_L1} />
              <mesh geometry={nodes.Object_109.geometry} material={materials.M_Basic} />
              <mesh geometry={nodes.Object_110.geometry} material={materials.Plastic_L1} />
              <mesh geometry={nodes.Object_111.geometry} material={materials.Plastic_Base} />
            </group>
            <group rotation={[0, 0, -Math.PI / 2]} scale={0.28}>
              <mesh geometry={nodes.Object_113.geometry} material={materials.M_L1} />
              <mesh geometry={nodes.Object_114.geometry} material={materials.Metall_Basic} />
              <mesh geometry={nodes.Object_115.geometry} material={materials.Metall_D1} />
            </group>
            <group rotation={[0, 0, -Math.PI / 2]} scale={0.27}>
              <mesh geometry={nodes.Object_117.geometry} material={materials.Plastic_D1} />
            </group>
            <group rotation={[0, 0, -Math.PI / 2]} scale={0.27}>
              <mesh geometry={nodes.Object_119.geometry} material={materials.M_D1} />
              <mesh geometry={nodes.Object_120.geometry} material={materials.M_D2} />
              <mesh geometry={nodes.Object_121.geometry} material={materials.Plastic_D1} />
              <mesh geometry={nodes.Object_122.geometry} material={materials.Plastic_Base} />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.28}>
              <mesh geometry={nodes.Object_124.geometry} material={materials['Material.008']} />
            </group>
            <group rotation={[-0.77, 0, 0]} scale={0.28}>
              <mesh geometry={nodes.Object_126.geometry} material={materials['Material.004']} />
              <mesh geometry={nodes.Object_127.geometry} material={materials.Grey_D2} />
              <mesh geometry={nodes.Object_128.geometry} material={materials.Plastic_D1} />
              <mesh geometry={nodes.Object_129.geometry} material={materials.Rubber_Basic} />
              <mesh geometry={nodes.Object_130.geometry} material={materials.Plastic_L1} />
              <mesh geometry={nodes.Object_131.geometry} material={materials.Plastic_Base} />
              <mesh geometry={nodes.Object_132.geometry} material={materials.Plastic_D2} />
              <mesh geometry={nodes.Object_133.geometry} material={materials.Yellow_L1} />
            </group>
            <group rotation={[-1.33, 0, 0]} scale={0.28}>
              <mesh geometry={nodes.Object_135.geometry} material={materials['Material.011']} />
              <mesh geometry={nodes.Object_136.geometry} material={materials['Material.012']} />
            </group>
            <group rotation={[0.27, 1.04, -2.02]} scale={0.28}>
              <mesh geometry={nodes.Object_138.geometry} material={materials.material} />
            </group>
            <group rotation={[-2.5, 1.21, 0.61]} scale={0.28}>
              <mesh geometry={nodes.Object_140.geometry} material={materials.material} />
            </group>
            <group rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.28, 0.31, 0.28]}>
              <mesh geometry={nodes.Object_142.geometry} material={materials.Metall_Basic} />
              <mesh geometry={nodes.Object_143.geometry} material={materials.Metall_D1} />
              <mesh geometry={nodes.Object_144.geometry} material={materials.Metall_D2} />
            </group>
            <group rotation={[-2.59, 0, -Math.PI]} scale={0.28}>
              <mesh geometry={nodes.Object_146.geometry} material={materials.Metall_Basic} />
              <mesh geometry={nodes.Object_147.geometry} material={materials.Metall_D1} />
              <mesh geometry={nodes.Object_148.geometry} material={materials.Metall_D2} />
            </group>
            <group scale={0.28}>
              <mesh geometry={nodes.Object_150.geometry} material={materials.CARBONE} />
              <mesh geometry={nodes.Object_151.geometry} material={materials['Material.001']} />
            </group>
            <group scale={[0.27, 0.28, 0.28]}>
              <mesh geometry={nodes.Object_153.geometry} material={materials.Rubber_Basic} />
            </group>
            <group rotation={[0, -Math.PI / 2, 0]} scale={0}>
              <mesh geometry={nodes.Object_155.geometry} material={materials['Material.002']} />
              <mesh geometry={nodes.Object_156.geometry} material={materials['Material.001']} />
            </group>
            <group rotation={[0, -Math.PI / 2, 0]} scale={0}>
              <mesh geometry={nodes.Object_158.geometry} material={materials['Rubber_Tire.002']} />
            </group>
            <group rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.28}>
              <mesh geometry={nodes.Object_160.geometry} material={materials['Material.007']} />
            </group>
            <group position={[0.02, 0.44, 0]} scale={0.28}>
              <mesh geometry={nodes.Object_162.geometry} material={materials.M_L1} />
              <mesh geometry={nodes.Object_163.geometry} material={materials.CARBONE} />
              <mesh geometry={nodes.Object_164.geometry} material={materials.M_D1} />
              <mesh geometry={nodes.Object_165.geometry} material={materials.M_D2} />
              <mesh geometry={nodes.Object_166.geometry} material={materials.Red_Basic} />
              <mesh geometry={nodes.Object_167.geometry} material={materials['Material.010']} />
            </group>
            <group rotation={[-0.11, 0, 0]} scale={0.28}>
              <mesh geometry={nodes.Object_169.geometry} material={materials['Material.015']} />
            </group>
          </group>
          <group position={[0.49, 1.37, 0.37]} rotation={[0.51, 0, -Math.PI / 2]} scale={0.13}>
            <mesh geometry={nodes.Object_171.geometry} material={materials['Material.002']} />
          </group>
          <group position={[-0.49, 0.87, 0.06]} rotation={[0.55, 0, Math.PI / 2]} scale={0.13}>
            <mesh geometry={nodes.Object_173.geometry} material={materials['Material.002']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/drone.gltf')
